# Generated by Django 5.0.6 on 2024-06-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guestList',
            field=models.ManyToManyField(blank=True, related_name='invited_to_event', to='accounts.subscriber'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ticketinfo'),
        ),
    ]
