# Generated by Django 5.0.6 on 2024-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_guestlist_alter_event_ticketinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='is_big',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='vip_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
