# Generated by Django 5.0.6 on 2024-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventticket_buyer_alter_eventticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
