# Generated by Django 5.0.6 on 2024-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventticket_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='descirption',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adip euismod er at, sed diam nonumy eirmod tempor incididunt ut labore et dolore magna aliqu compliance et justo euismod. Ut enim ad minim veniam et aliqu', max_length=2048, null=True),
        ),
    ]
